language: node_js
node_js:
   - 13

services:
   - docker

install: 
   - echo 'npm install dependencies'

before_script: 
   - echo 'no tests'

script: 
   - docker --version
   - docker build -t simple-node-ci .
   - docker tag simple-node-ci grace22/simple-node-ci:latest

after_success: 
   - echo  '$DOCKER_PASSWORD' | docker login -u '$DOCKER_USERNAME' --password-stdin
   - docker push grace22/simple-node-ci         

